spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
info:
  application:
    os: ${os.name}
---
spring:
  config:
    activate:
      on-profile: local
info:
  application:
    platform: Local Machine
    space: local-development
---
spring:
  config:
    activate:
      on-profile: heroku
info:
  application:
    platform: Heroku
    space: ${space.name}